// <auto-generated />
namespace ImageMaker.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TemplatesImages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TemplatesImages));
        
        string IMigrationMetadata.Id
        {
            get { return "201509122221015_TemplatesImages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
