// <auto-generated />
namespace ImageMaker.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_last_photo_time : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_last_photo_time));
        
        string IMigrationMetadata.Id
        {
            get { return "201604141128158_Add_last_photo_time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
